### ISSUE TITLE
Folders

### ISSUE THREAD

**Issue by crutchcorn** [materialos/Linux-Icon-Pack#1]
http://numixproject.github.io/blog/2015/01/31/folders-folders-folders-they-are-ready-for-your-love.html

For names and reference

**Comment by danielhickman** [comment]
Should we be making more folders? I'm not sure what you want to reference.

**Comment by crutchcorn** [comment]
No no, don't worry. :) I'll take care of this. I just need to know the names of the folders okay? :P No sweat

**Comment by deadbaed** [comment]
@crutchcorn I'm wondering who found this... :P

**Comment by germanfr** [comment]
I did some folders for images, etc, following the one that was made (downloads). Wondering if I can upload...
![screenshot from 2015-08-31 13 51 14](https://cloud.githubusercontent.com/assets/10391266/9578097/7c7816ea-4fe7-11e5-923c-c19f5d07c6f5.png)

**Comment by deadbaed** [comment]
looks good for me!
just delete the links for the download icon and submit a pull request! :)

**Comment by crutchcorn** [comment]
@german6 You are totally welcome to submit a pull request! :D Thanks for your support!

**Comment by germanfr** [comment]
@crutchcorn @loctauxphilippe I'm sorry but I'm new to github and it looks there's no way I can push any pull request or branch or I don't know, and I don't want to damage anything. Any help? :(

**Comment by danielhickman** [comment]
@german6 You should fork this repo to your GitHub profile and then push to it ;)

**Comment by germanfr** [comment]
@danielhickman finally done. Thank you :+1:

**Comment by deadbaed** [comment]
@german6 @materialos/linux-team I just pushed your icons with the good names :)
they may look a little bit blurry, I just have to export them in a bunch of sizes :)
