### ISSUE TITLE
problem with inkscape

### ISSUE THREAD

**Issue by deadbaed** [materialos/Linux-Icon-Pack#14]
there's a color issue if you use the atom-dock by ozonos:

![screenshot from 2015-09-05 19-53-25](https://cloud.githubusercontent.com/assets/8809909/9700574/e7f5747a-5407-11e5-87e3-e79d2b61e5c9.png)

**Comment by germanfr** [comment]
But this is the same problem with the original icon? I mean not themed?

**Comment by deadbaed** [comment]
nope
![screenshot from 2015-09-05 19-57-54](https://cloud.githubusercontent.com/assets/8809909/9700584/695a5c56-5408-11e5-9663-67c00d685dfa.png)

**Comment by germanfr** [comment]
Try with this one. Cannot make it darker.
[SVG here](https://drive.google.com/open?id=0B2XBXNycZLFYUWtNTWlsNG44eXc) 
![inkscape-darker](https://cloud.githubusercontent.com/assets/10391266/9700851/548622aa-5413-11e5-9d0c-34bedb41ea08.png)

**Comment by deadbaed** [comment]
the icon doesn't show up :(

**Comment by crutchcorn** [comment]
Add a very light gray 100 outline or something if need be

**Comment by germanfr** [comment]
Judge by yourselves
![inkscape_light](https://cloud.githubusercontent.com/assets/10391266/10049182/aa6b0e72-6216-11e5-9f07-941788fdcd2f.png) ![screenshot from 2015-09-23 17 17 34](https://cloud.githubusercontent.com/assets/10391266/10049262/1743428a-6217-11e5-804a-4e86f1f58e89.png)

**Comment by crutchcorn** [comment]
Mmm.... I don't think I like the outline... I think that it should just stay the way that it is... :/

**Comment by germanfr** [comment]
Uploaded the darker icon without the outline: [here is the pull request](https://github.com/materialos/Linux-Icon-Pack/pull/30)

**Comment by danielhickman** [comment]
Can this be closed? It is already pulled to master.

**Comment by deadbaed** [comment]
someone have to proove it that it finally works

**Comment by germanfr** [comment]
![Proof](https://cloud.githubusercontent.com/assets/10391266/10049262/1743428a-6217-11e5-804a-4e86f1f58e89.png)
