### ISSUE TITLE
Icon for Papyros's Taskly Application

### ISSUE THREAD

**Issue by dominicap** [materialos/Linux-Icon-Pack#2]
My suggestion is a clipboard with checkmarks

**Comment by crutchcorn** [comment]
Can I have a picture of the application and the picture of the current icon?

**Comment by dominicap** [comment]
As far as I know I do not think Taskly has an icon.

Link to the code: https://github.com/iBeliever/taskly

Here is the picture: 
![fullscreen_3_3_15__10_10_pm](https://cloud.githubusercontent.com/assets/13564850/9287558/d4072a54-42e0-11e5-87f7-cde42a61e985.png)

**Comment by deadbaed** [comment]
it would be nice to have an icon first

**Comment by deadbaed** [comment]
closing this for the moment until we have an icon
