### ISSUE TITLE
Where to put the wifi icons

### ISSUE THREAD

**Issue by germanfr** [materialos/Linux-Icon-Pack#21]
Well, I have looked in some packs installed on my Linux but each one has them on a different place. I'll put down below how is it rght now. All are svg files:
- gnome: /scalable/status
- Paper: 
  - /symbolic/status
  - and /sizexsize/panel (only small sizes)
- Mint-X: /status/scalable (in reverse as gnome)
- Faenza: same as Mint-X

The icons are done, I'll do a pull request as soon as I know the place to put them.

**Comment by deadbaed** [comment]
I'll do some research
if anyone wants to do it, let's go :)

**Comment by germanfr** [comment]
I've been investigating and I found they must be in the devices folder. See [the freedesktop spec](https://specifications.freedesktop.org/icon-naming-spec/icon-naming-spec-latest.html).
 * network-wireless colored in all sizes
 * network-wireless-symbolic in the symbolic folder (for the panels).

Since I don't have the same computer and I lost the icons, I'll close this.

**Comment by deadbaed** [comment]
no problem :)
