### ISSUE TITLE
Arch install error

### ISSUE THREAD

**Issue by gerep** [materialos/Linux-Icon-Pack#27]
The PKGBUILD file is trying to copy the directory **Materialos**, which is wrong, should be **MaterialOS**

In this line: `cp -dr --no-preserve='ownership' Materialos "$pkgdir"/usr/share/icons/`

**Comment by deadbaed** [comment]
thanks :)

**Comment by deadbaed** [comment]
it's fixed

**Comment by gerep** [comment]
Awesome! ;)
