### ISSUE TITLE
Cursor theme for Linux

### ISSUE THREAD

**Issue by dominicap** [materialos/Linux-Icon-Pack#3]
A material cursor theme for Papyros.

**Comment by deadbaed** [comment]
good idea! @materialos/owners have to create a new repo since I can't do that :tongue: 
I'm pretty we are able to make that happen :)

**Comment by dominicap** [comment]
Great!

**Comment by danielhickman** [comment]
What should the repo say? @loctauxphilippe

**Comment by danielhickman** [comment]
https://github.com/materialos/Linux-Cursor-Theme

**Comment by deadbaed** [comment]
We can close the issue, the repo has been created.
@domi-a-philip I'll work on it asap :)

**Comment by dominicap** [comment]
@loctauxphilippe  Thanks!

**Comment by deadbaed** [comment]
@domi-a-philip :+1:
