### ISSUE TITLE
Folder Icons Fails to Shrink

### ISSUE THREAD

**Issue by dominicap** [materialos/Linux-Icon-Pack#33]
Folders fail to re-size.

I think for the special folders, 24x24 and below should just be the label/symbol instead of the whole symbol and folder.

![screenshot from 2015-09-26 22 46 38](https://cloud.githubusercontent.com/assets/13564850/10120902/f8080464-64a0-11e5-98aa-873a8cbb5c40.png)

**Comment by deadbaed** [comment]
work for me

![screenshot from 2015-09-27 11-27-14](https://cloud.githubusercontent.com/assets/8809909/10122065/be4f463c-650a-11e5-892f-11f5542d4d7b.png)

**Comment by deadbaed** [comment]
we need to create the symbolic of these places icons

**Comment by dominicap** [comment]
Fixed if you are using the latest version
