### ISSUE TITLE
Extra libreoffice icons

### ISSUE THREAD

**Issue by deadbaed** [materialos/Linux-Icon-Pack#34]
to complete the libreoffice suite with our icons, we need:
- [x] libreoffice
- [x] libreoffice-draw
- [x] libreoffice-math

**Comment by germanfr** [comment]
This one for LibreOffice main app?
![libreoffice](https://cloud.githubusercontent.com/assets/10391266/10125372/d4227800-6571-11e5-97f0-be679fe36b38.png) ![](http://emmabuntus.sourceforge.net/icones/libreoffice.png)

**Comment by crutchcorn** [comment]
Nah @german6. I'll make the libreoffice icons! :)

**Comment by germanfr** [comment]
OK @crutchcorn but if you are doing all see if you can find another use for the ones that are already done.
