### ISSUE TITLE
Makefile dynamic folder handling

### ISSUE THREAD

**Issue by crutchcorn** [materialos/Linux-Icon-Pack#56]
I would like to make a script that takes all the numbers of folders and runs the appropriate commands based on that

**Comment by germanfr** [comment]
Something like this will do the work in this case:

``` bash
for d in */; do
    #Do whatever with $d as directory
done
```

But as I don't know how Makefile works I can't add it to the code. I don't want to mess it all.

**Comment by crutchcorn** [comment]
Exactly @germanfr. I will wait until @ploctaux gets back to help us figure out what we want

**Comment by deadbaed** [comment]
what do you want?

**Comment by crutchcorn** [comment]
We want to be able to do something where the number of folders is calculated and then the makefile is updated with that info and changed dynamically. I'll write a demo to showcase my point

**Comment by crutchcorn** [comment]
An example is made in #59

**Comment by deadbaed** [comment]
we'll work on that

**Comment by deadbaed** [comment]
well I think it won't work (my knowledge of makefile is still new) and I think it's better to have it exactly what we want
close issue and pr?

**Comment by crutchcorn** [comment]
Yeah, not possible AFAIK. Closing the issue. Sorry for raising hopes, guys

**Comment by deadbaed** [comment]
I didn't have any hope XD jk
