### ISSUE TITLE
new folder icons

### ISSUE THREAD

**Issue by deadbaed** [materialos/Linux-Icon-Pack#6]
we need more folder icons!
go to "/usr/share/icons/Adwaita/48x48/places"
I need please these icons:

folder-remote
folder-saved-search
network-server
network-workgroup
start-here
user-bookmarks
user-trash

please make them 48x48 in svg
name them correctly if possible, I'll appreciate that :)
push them into Materialos/48x48/places/svg

**Comment by dominicap** [comment]
I made a blue-grey one for network-server. I'll try to make more blue-grey ones and convert the blue-grey folders to 48x48 and rename them.

**Comment by deadbaed** [comment]
@domi-a-philip so you would suggest to change all the folder icons to the blue-grey color?

**Comment by deadbaed** [comment]
@domi-a-philip btw, do you have telegram or hangouts to chat to talk about the icons?
I'm @ploctaux on telegram and Philippe Loctaux on Hangouts :)

**Comment by germanfr** [comment]
I did some more brown ones. I'll do a pull request when I finish.

**Comment by dominicap** [comment]
@loctauxphilippe I really like both the blue-grey and brown but speaking specifically for Papyros, I think the blue grey ones will look better. The brown ones may look better for other distros such as Ubuntu since theme generally is brown and orange. Maybe the blue-grey ones can be exclusively for Papyros....

**Comment by deadbaed** [comment]
@german6 no problem! :)

**Comment by deadbaed** [comment]
Wow it's fast!
- [x] folder-remote
- [x] folder-saved-search
- [ ] network-server
- [ ] network-workgroup
- [ ] start-here
- [x] user-bookmarks
- [ ] user-trash

**Comment by deadbaed** [comment]
plus there's a new icon:
user-trash-full
please :)

**Comment by germanfr** [comment]
@loctauxphilippe  What is start-here?

**Comment by deadbaed** [comment]
It's the "start button" like on the picture (pic attached)

I think we should use the Materialos logo, because it looks like beautiful! What do you think @crutchcorn?

![bayin](https://cloud.githubusercontent.com/assets/8809909/9693594/d64598d8-5351-11e5-8fcb-3a108a3644e6.jpg)

**Comment by crutchcorn** [comment]
I think we should make two different folders for different color folders. Then the user can change the folder color just by moving a few folders. I want many different color folders - including teal and orange, amongst others. I will spearhead that change right now

**Comment by dominicap** [comment]
@crutchcorn Do you like to Blue-Grey ones I made?

**Comment by crutchcorn** [comment]
Love em @domi-a-philip

**Comment by crutchcorn** [comment]
@loctauxphilippe I argue that we should make individual "start" buttons per OS.

**Comment by dominicap** [comment]
Haha Thanks :) I think the Blue-Grey folders would be nice for Papyros to have if @iBeliever likes them too. I also have more coming ;)

**Comment by dominicap** [comment]
@loctauxphilippe I also agree with @crutchcorn Cant really make generic start icons

**Comment by crutchcorn** [comment]
@domi-a-philip You actually can make a generic start icon. Let me give it a shit. Fair warning to the EvoPop team, it will take inspiration from the EvoPop icon but will not be based off of it

**Comment by crutchcorn** [comment]
I will be making multicolor folders but I would like to know what color @iBeliever thinks is best as well

**Comment by deadbaed** [comment]
well guys the problem is that you can't have one custom icon for start per os, it's one icon, and nothing else, but if we leave this icon uncovered we can't say our theme is full :(

**Comment by crutchcorn** [comment]
I can make a generic start icon. Don't worry y'all

**Comment by crutchcorn** [comment]
Sorry, did not mean to close

**Comment by dominicap** [comment]
Can I clean up the repo a bit? I think we should reorganize based on colors since we are planning on adding more colors. I'll make sure to add the other icons that are not folders are added

**Comment by crutchcorn** [comment]
@domi-a-philip No thank you... Please message me on G+

**Comment by dominicap** [comment]
So sorry I'll revert it ASAP

**Comment by crutchcorn** [comment]
Thank you.

**Comment by deadbaed** [comment]
If you need help for sorting icons, I can help you cause I'm here to sort the icons to make them work 😊

**Comment by dominicap** [comment]
Is it fixed @crutchcorn?

**Comment by crutchcorn** [comment]
Yes it is. Could you please still message me on hangouts so that we can all chat live?

**Comment by domi-a-philip** [comment]
@crutchcorn Okay

**Comment by domi-a-philip** [comment]
I'll start it now

**Comment by deadbaed** [comment]
I'll close this issue and open a new one, to clean up for icons requests
