### ISSUE TITLE
otter-browser icon

### ISSUE THREAD

**Issue by mkljczk** [materialos/Linux-Icon-Pack#65]
- [Otter Browser](https://github.com/OtterBrowser/otter-browser)
- Project that aims to recreate the best aspects of the classic Opera (12.x) UI using Qt5
- `Icon=otter-browser`
![10384419](https://cloud.githubusercontent.com/assets/21127288/24331480/9c76167e-1235-11e7-9012-0a64312e877f.png)

**Comment by deadbaed** [comment]
thank you for the request

**Comment by ghost** [comment]
sorry guys I might not be in the right place, I have no idea whty I am here. I posted a repository but i dont know even know exactly what it is. All I know is that I keep feeling I have no control on my computer.

**Comment by crutchcorn** [comment]
@Skuff1975 I think you might be in the wrong place. Are you having general computer issues or Github issues?

For the first, I might suggest this video which seems useful:
https://www.youtube.com/watch?v=JwkngJQNgoY

For the second, I'd suggest taking a look at Github's guides for Git and their website:
https://guides.github.com/
